### ISSUE TITLE
command_line changes to configuration.yaml

### ISSUE THREAD

**Issue by harvybob** [GivEnergy-GivTCP-Users-Community/Agile-Incoming-inverter-control#4]
Hi,
With the 2023.6.1 release of HA, there are some changes needed to the configuration.yaml

The old layout is:
```
- platform: command_line
  command: "python3 /config/pyscripts/get_agile_incoming_ordered.py"
  scan_interval: 315360000 
  value_template: '{{value_json.Run_number1}}'
  json_attributes:
    - Run_number1
    - Run_number2
    - Run_number3
    - Run_number4
...
```

The new layout needs the entry command_line:
```
command_line:
  - sensor:
      command: "python3 /config/pyscripts/get_agile_incoming_ordered.py"
      scan_interval: 315360000 
      value_template: '{{value_json.Run_number1}}'
      json_attributes:
        - Run_number1
        - Run_number2
        - Run_number3
        - Run_number4
```

Note that the indentation also needs to change!
